name: DevCard

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: gabriel-hrs/gabriel-hrs@1.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
